#!/bin/sh
losetup -a
losetup -d /dev/loop*

ARCHS="i586 x86_64"
#ARCHS="x86_64"
#ARCHS="i586"

#if [ ! "$UID" = "0" ]; then#
#	echo "Restarting as root.."
#	exec sudo $0
#fi

# a temporary hack to make python 2.6 work
#export PYTHONPATH=/usr/lib/python2.6/site-packages/

DIRNAME=$(dirname $0)
cd $DIRNAME

build_root="./"

d=`date +%Y.%m.%d-%H.%M`

product_id="ROSA.2012.Desktop.Beta"
product_name_file="${build_root}/.name.txt" ; touch ${product_name_file}

#ks="${build_root}/${product_id}/.ks"

ks="${build_root}/.ks"
counter="${build_root}/.counter"
menu="${build_root}/.menu.xml"

touch ${counter}

i=`cat ${counter}`
i=`expr $i + 1`

echo $i > ${counter}

echo "$i.$d" > ${build_root}/version.txt

# build different architectures

for arch in $ARCHS; do
	cp -f ${ks}.template ${ks}
	sed -i -e "s:#ARCH#:$arch:g" ${ks}
	sed -i -e "s:#PATH#:${build_root}/:g" ${ks}
	sed -i -e "s:#PATH#:${build_root}/:g" ${menu}

	mkdir -p $build_root/iso/${product_id}/
	livecd-creator --config=${ks} --fslabel=${product_id}.$arch --menu-config=${build_root}/.menu.xml --tmpdir=/share/temp/ -d -v

	mv ${product_id}.$arch.iso $build_root/iso/${product_id}/
	isohybrid $build_root/iso/${product_id}/${product_id}.$arch.iso
	md5sum  $build_root/iso/${product_id}/${product_id}.$arch.iso > $build_root/iso/${product_id}/${product_id}.$arch.iso.md5sum

	echo ""
	echo "          ALL DONE!        $build_root/iso/${product_id}/${product_id}.$arch.iso"
	echo ""
done
